### ISSUE TITLE
ReferenceError: Auth0 is not defined

### ISSUE THREAD

**Issue by byrneciaran** [auth0/angular-auth0#18]
I have a bare bones angular app running angular 1.6.4.

I ran `bower install auth0.js angular-auth0  --save` and my index.html looks like this:

```
<script type="text/javascript" src="/vendor/angular/angular.js"></script>
<script type="text/javascript" src="/vendor/auth0.js/build/auth0.js"></script>
<script type="text/javascript" src="/vendor/angular-auth0/dist/angular-auth0.js"></script>
<script type="text/javascript" src="/app/app.js"></script>
```

My app.js looks like this:

`var app = angular.module('app', ['auth0.auth0']);`

My bower versions are:

    "angular": "^1.6.4",
    "auth0.js": "^8.7.0",
    "angular-auth0": "^1.0.7"

I'm getting the error:

ReferenceError: Auth0 is not defined
    at new angularAuth0 (http://localhost:8081/vendor/angular-auth0/dist/angular-auth0.js:10:29)
    at Object.instantiate (http://localhost:8081/vendor/angular/angular.js:5018:14)
    at provider (http://localhost:8081/vendor/angular/angular.js:4826:36)
    at Object.provider (http://localhost:8081/vendor/angular/angular.js:4818:16)
    at runInvokeQueue (http://localhost:8081/vendor/angular/angular.js:4890:35)
    at http://localhost:8081/vendor/angular/angular.js:4899:11
    at forEach (http://localhost:8081/vendor/angular/angular.js:403:20)
    at loadModules (http://localhost:8081/vendor/angular/angular.js:4880:5)
    at http://localhost:8081/vendor/angular/angular.js:4898:40
    at forEach (http://localhost:8081/vendor/angular/angular.js:403:20)

**Comment by chenkie** [comment]
you'll need angular-auth0 2.0 beta.

```
npm install angular-auth0@beta
```
